title: "Xiaojia Wang"
author: "Xiaojia Wang"
description: "Purdue University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "https://xiaojia-wang.github.io/cv/"}
  - {title: "Research"}
  - {title: "Publications", file: "publications.md"}
  - {title: "News"}
  - {title: "Contact"}
  #- {file: "index.html"}
  #- {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:wang4142@purdue.edu"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/xiaojia-wang-03160314a/"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
